# HTTP Server
server:
  port: 19001  # HTTP (Tomcat) port

spring:
  application:
    name: ts-payment-service
  data:
    mongodb:
      host: ts-payment-mongo
      database: ts
      port: 27017
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0