# HTTP Server
server:
  port: 14568  # HTTP (Tomcat) port

spring:
  application:
    name: ts-preserve-service
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
