spring:
  application:
    name: ts-price-service
  data:
    mongodb:
      host: ts-price-mongo
      database: ts
      port: 27017
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0

# HTTP Server
server:
  port: 16579  # HTTP (Tomcat) port