server:
  port: 18856

spring:
  application:
    name: ts-food-service
  data:
    mongodb:
      host: ts-food-mongo
      database: ts
      port: 27017
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0