server:
  port: 18673

spring:
  application:
    name: ts-inside-payment-service

  data:
    mongodb:
      host: ts-inside-payment-mongo
      database: ts
      port: 27017
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0